url: https://imr-framework.github.io
baseurl:

# Site settings
title: imr-framework
email: imr.framework2018@gmail.com
description: "imr-framework"
# --------- NEW SECTION --------- #
# This section contains the main settings for the site, including title, email, and description.
# This is the main title of the site, which will appear in the header and browser title bar.
# The email address is used for contact purposes and can be displayed on the site.
# The description provides a brief overview of the site and can be used in search engine optimization (SEO).
# Note: Ensure to keep the title, email, and description concise and relevant to the content of the site.
# Team names, titles and social links
people:
- name: Sairam Geethanath
  pic: 1
  position: Principal Investigator
  social:
    - title: google-scholar
      url: https://scholar.google.com/citations?user=isw_o1YAAAAJ&hl=en&oi=ao

- name: Ivan Etoku Oiye
  pic: 9
  position: Trainee (BSc, Biomedical Engineering)
  social:
    - title: google-scholar
      url: https://scholar.google.com/citations?hl=en&user=A7HuxwcAAAAJ

- name: Ajay Sharma
  pic: 25
  position: Post-doctoral Fellow
  social:
    - title: google-scholar
      url: https://scholar.google.com/citations?hl=en&user=rojRnpEAAAAJ

# Alumni names, titles and social links
alumni:
- name: Shounak Nandi
  pic: 8
  position: Neuroimaging researcher, Albert Einstein College of Medicine
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/shounak-nandi-b2b40b78/
  
- name: Kunal Aggarwal
  pic: 7
  position: Master's thesis, Max Planck Institute for Biological Cybernetics, Tübingen, Germany
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/kunal-aggarwal-neuro-engineer/

- name: Marina Jimeno Manso
  pic: 6
  position: Clinical Imaging Scientist, Novartis
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/marina-manso-jimeno/


- name: Keerthi Sravan Ravi
  pic: 5
  position: Senior AI Scientist, GE Healthcare
  social:
  - title: linkedin
    url: http://linkedin.com/in/sravan953/


- name: Enlin Qian
  pic: 3
  position: Post-doctoral Fellow, Dr. Ricardo Otazo Lab, Memorial Sloan Kettering Cancer Center
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/enlin-qian-890659111/

- name: Pavan Poojar
  pic: 2
  position: Post-doctoral Fellow, Dr. Hurd Lab, Icahn School of Medicine at Mount Sinai
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/pavan-poojar-3a399a23/

- name: Rakshith Shanbhag
  pic: 11
  position: Product Manager, Sysmex Europe
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/rakshith-shanbhag-a261b661/

- name: Nutandev Bikkamane Jayadev
  pic: 12
  position: Research Scientist, Siemens Healthineers
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/nutandevbjayadev/

- name: Imam Ahmed Shaik
  pic: 13
  position: General Manager, Siemens Healthineers
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/imam-ahmed-shaik-99a19050/

- name: Amaresha Shridhar Konar
  pic: 14
  position: MR Platform Team Lead, Columbia University in the City of New York
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/amaresha-konar-shridhar/

- name: Ssentamu Tonny 
  pic: 15
  position: Graduate Research Student, King's College London
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/ssentamu-tonny/

# Note: The pic numbers above should correspond to images in the /assets/images/people/ directory.
- name: Rahul Ramesh
  pic: 16
  position: AI Researcher, Siemens Healthineers
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/rahul-ramesh-b7922397/
  # Note: Ensure to add an image named '4.jpg' in the /assets/images/people/ directory for this person.

- name: Vineet Vinay Bhombore
  pic: 17
  position: Research Scientist, Siemens Healthineers
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/vineet-vinay-bhombore-79aa14131/
  # Note: Ensure to add an image named '17.jpg' in the /assets/images/people/ directory for this person.

- name: Nishika Girish
  pic: 18
  position: James Scholar, University of Illinois at Urbana-Champaign (UIUC) 
    # Note: This person is a current student and not an alumnus, but included for completeness.
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/nishikagirish/
  # Note: Ensure to add an image named '18.jpg' in the /assets/images/people/ directory for this person.

- name: Rishi Ananth
  pic: 19
  position: Honors, Chemistry, University of Washington at Seattle
    # Note: This person is a current student and not an alumnus, but included for completeness.
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/rishiananth/
  # Note: Ensure to add an image named '19.jpg' in the /assets/images/people/ directory for this person.

- name: Alvin Kombawa
  pic: 20
  position: MASc, Biomedical Engineering, University of British Columbia (UBC)
    # Note: This person is a current student and not an alumnus, but included for completeness.
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/alvin256/
  # Note: Ensure to add an image named '20.jpg' in the /assets/images/people/ directory for this person.

- name: Sai Abitha Srinivas
  pic: 21
  position: Principal MR Systems Engineer, Adialante
    # Note: This person is a current student and not an alumnus, but included for completeness.
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/sai-abitha-srinivas/
  # Note: Ensure to add an image named '21.jpg' in the /assets/images/people/ directory for this person.

- name: Arush Honnedevasthana Arun
  pic: 22
  position: Research Fellow, The National Imaging Facility
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/arush-honnedevasthana-arun-a315257a/

- name: Manoj B
  pic: 23
  position: MRI Pulse Programming R&D, Philips Healthcare
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/manoj-b-500b99114/

- name: Jayashree Ganguly
  pic: 24
  position: Senior Development Engineer, Philips Innovation Campus
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/jayashree-ganguly-a5aa9bb5/

# The section below contains the details of the projects associated with the imr-framework.
# Each project can have a title, description, image, and other details.
# Note: The pic numbers above should correspond to images in the /assets/images/projects/ directory.

past:
- title: Indian National Mission on Indigenous 1.5T MRI - Academic and prototyping site
  description: "We were involved in building a 1.5T MRI from scratch indigenously in India."
  github: 
  sponsor: Dept. of Electronics and Information Technology (DeitY), Government of India
  students: 
  thumbnail: SAMEER.png
 
- title: Pediatric brain tumor imaging using tailored MR Fingerprinting
  description: "We developed a non-synthetic approach to simultaneously obtain multiple qualitative and qunatitative MR images. We designed, implemented and evaluated the sequence on pediatric brain tumor patients"
  github: 
  sponsor: General Electric (GE) Healthcare
  students: 
  thumbnail: TMRF.png


# ---------------------------------- NEW SECTION ---------------------------------- #
# Note: The following section is for projects. Each project can have a title, description, image, and other details.
# This section allows you to showcase various projects associated with the imr-framework.
# Each project can be displayed with a title, description, image, and other relevant details.
# Note: The pic numbers above should correspond to images in the /assets/images/projects/ directory.
# Note: Ensure to add images for each project in the /assets/images/projects/ directory with names corresponding to the pic numbers (e.g., 1.jpg, 2.jpg, etc.)
# Note: The pic numbers above should correspond to images in the /assets/images/projects/ directory.
# Note: Ensure to add images for each project in the /assets/images/projects/ directory with names corresponding to the pic numbers (e.g., 1.jpg, 2.jpg, etc.)
# Projects
projects:
- title: Practical magnetic resonance imaging for all 
  description: "This educational project will overcome access limitations and deliver a seminal, cutting-edge curriculum using an online game-based digital platform that allows students to build and play with their own educational MR scanner."
  github: https://github.com/delta-diy-mri/delta-diy-mri.github.io
  sponsor: JHU Provost's DELTA Award
  students: Ivan Etoku Oiye
  thumbnail: Delta_Logo.png

- title: Design and development of 0.2T portable MR systems
  description: "Successful design and development of a portable 0.2T MRI for the head and spine will yield structural, functional and metabolic MRI capabilities required for downstream clinical use in an accessible manner."
  sponsor: Medirays Pvt. Ltd.
  students: Ivan Etoku Oiye
  thumbnail: Medirays_pic.jpg
  
- title: Accessible imaging of high consequence pathogens
  description: "Tracking brain changes due to infection in restricted environments require portable solutions providing image quality similar to clinical scanners"
  sponsor: 
  students: Ivan Etoku Oiye, Ajay Sharma
  thumbnail: NiV_summary.png

# - title:  Tracking structural brain changes at 0.05T 
#   description: "UPCOMING - Tracking brain changes using low-field MRI at 3T performance will enable monitoring of neurological disorders in rural settings"
#   sponsor: 
#   students: Ajay Sharma
#   thumbnail: 

# - title: Automated response assessment in pediatric neuro-oncology (Auto-RAPNO)
#   description: "UPCOMING - Automating the workflow for RAPNO will augment neuro-oncologists in rural settings"
#   sponsor: 
#   students: Ajay Sharma
#   thumbnail: 

# - title: Automated response assessment in pediatric neuro-oncology (Auto-RAPNO)
#   description: "UPCOMING - Automating the workflow for RAPNO will augment neuro-oncologists in rural settings"
#   sponsor: 
#   students: Ajay Sharma
#   thumbnail: 

publication:
- citation: Oiye, I.E., Poojar, P., Qian, E., Vaughan, J.T. and Geethanath, S., 2025. A standalone and cost-effective MR-compatible computer numerical control machine for simultaneous, multi-parameter mapping. Measurement Science and Technology, 36(4), p.045902.
  url: https://iopscience.iop.org/article/10.1088/1361-6501/adbb09/meta
  num: 1)

- citation: Manso Jimeno, M., Ravi, K.S., Fung, M., Oyekunle, D., Ogbole, G., Vaughan Jr, J.T. and Geethanath, S., 2025. Automated detection of motion artifacts in brain MR images using deep learning. NMR in Biomedicine, 38(1), p.e5276.
  url: https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/abs/10.1002/nbm.5276
  num: 2)

- citation: Block, K.T., Zhang, C., Ciancia, V., Cooley, C., Geethanath, S., Stockmann, J., Verghese, G. and Alon, L., 2025. MRI4ALL - A Week‐Long Hackathon for the Development of an Open‐Source Ultra‐Low‐Field MRI System. Journal of Magnetic Resonance Imaging.
  url: https://onlinelibrary.wiley.com/doi/abs/10.1002/jmri.29771
  num: 3)

- citation: Poojar, P., Oiye, I.E., Aggarwal, K., Jimeno, M.M., Vaughan, J.T. and Geethanath, S., 2024. Repeatability of image quality in very low‐field MRI. NMR in Biomedicine, 37(10), p.e5198.
  url: https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/abs/10.1002/nbm.5276
  num: 4)

- citation: Tong, G., Ananth, R., Vaughan Jr, J.T. and Geethanath, S., 2024. Expanding access to magnetic resonance education through open-source web tutorials. NMR in Biomedicine, pp.e5109-e5109.  
  url: https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/10.1002/nbm.5109
  num: 5)

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/imr-framework

# Postal address (add as many lines as necessary)
address:
  - line: 600 N. Wolfe Street, Room 120
  - line: Baltimore, MD 21287

# Build settings
markdown: kramdown
permalink: pretty

